services:
  # PocketBase Database
  pocketbase:
    build:
      context: .
      dockerfile: docker/Dockerfile.pocketbase
    container_name: coderbot-pocketbase
    ports:
      - "8090:8090"
    volumes:
      # - pocketbase_data:/pb/pb_data  # Comentado para usar dados do Dockerfile
      - ./pocketbase_0.27.2_linux_amd64/pb_migrations:/pb/pb_migrations:ro
    environment:
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
    networks:
      - coderbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: coderbot-backend
    ports:
      - "8000:8000"
    environment:
      - DEEP_SEEK_API_KEY=${DEEP_SEEK_API_KEY}
      - DEEP_SEEK_API_URL=${DEEP_SEEK_API_URL}
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - POCKETBASE_URL=http://pocketbase:8090
      - POCKETBASE_USER_EMAIL=${POCKETBASE_USER_EMAIL}
      - POCKETBASE_USER_PASSWORD=${POCKETBASE_USER_PASSWORD}
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      # Judge0 local (prefer over RapidAPI)
      - LOCAL_JUDGE0_URL=http://judge0:2358
      # PostHog (server-side events opcional)
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST:-https://us.i.posthog.com}
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - coderbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: coderbot-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_POCKETBASE_URL=http://localhost:8090
      # PostHog (client-side)
      - VITE_POSTHOG_KEY=${VITE_POSTHOG_KEY}
      - VITE_POSTHOG_HOST=${VITE_POSTHOG_HOST:-https://us.i.posthog.com}
    depends_on:
      - backend
    networks:
      - coderbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Code Server IDE (opcional)
  code-server:
    image: codercom/code-server:latest
    container_name: coderbot-code-server
    ports:
      - "8787:8787"
    volumes:
      - ./:/home/coder/project
      - code_server_data:/home/coder/.local/share/code-server
    networks:
      - coderbot-network
    restart: unless-stopped
    command: --bind-addr 0.0.0.0:8787 --auth none /home/coder/project

  # Judge0 - Execução de código (API + DB + Redis)
  judge0-db:
    image: postgres:13
    container_name: coderbot-judge0-db
    environment:
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_DB=judge0
    networks:
      - coderbot-network
    restart: unless-stopped

  judge0-redis:
    image: redis:6-alpine
    container_name: coderbot-judge0-redis
    networks:
      - coderbot-network
    restart: unless-stopped

  judge0:
    image: judge0/judge0:1.13.0
    container_name: coderbot-judge0
    ports:
      - "2358:2358"
    environment:
      - DATABASE_URL=postgresql://judge0:judge0@judge0-db:5432/judge0
      - REDIS_URL=redis://judge0-redis:6379/0
      - REDIS_HOST=judge0-redis
      - REDIS_PORT=6379
      - SIDEKIQ_REDIS_URL=redis://judge0-redis:6379/0
      - QUEUE_REDIS_URL=redis://judge0-redis:6379/0
      - CACHE_REDIS_URL=redis://judge0-redis:6379/0
      - DISABLE_CACHE=false
      - RAILS_ENV=production
      - ALLOW_ORIGIN=*
      # Force options
      - ENABLE_WAIT_RESULT=true
      - ENABLE_COMPILER_OPTIONS=true
    depends_on:
      judge0-db:
        condition: service_started
      judge0-redis:
        condition: service_started
    networks:
      - coderbot-network
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2358/"]
      interval: 30s
      timeout: 10s
      retries: 3

  judge0-worker:
    image: judge0/judge0:1.13.0
    container_name: coderbot-judge0-worker
    environment:
      - DATABASE_URL=postgresql://judge0:judge0@judge0-db:5432/judge0
      - REDIS_URL=redis://judge0-redis:6379/0
      - RAILS_ENV=production
      - ALLOW_ORIGIN=*
    depends_on:
      judge0-db:
        condition: service_started
      judge0-redis:
        condition: service_started
    networks:
      - coderbot-network
    restart: unless-stopped
    command: bundle exec sidekiq -c 5 -q default -q high

volumes:
  # pocketbase_data:  # Comentado para usar dados do Dockerfile
  #   driver: local
  code_server_data:
    driver: local

networks:
  coderbot-network:
    driver: bridge