services:
  # PocketBase Database
  pocketbase:
    build:
      context: .
      dockerfile: docker/Dockerfile.pocketbase
    container_name: coderbot-pocketbase
    ports:
      - "8090:8090"
    volumes:
      # - pocketbase_data:/pb/pb_data  # Comentado para usar dados do Dockerfile
      - ./pocketbase_0.27.2_linux_amd64/pb_migrations:/pb/pb_migrations:ro
    environment:
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
    networks:
      - coderbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: coderbot-backend
    ports:
      - "8000:8000"
    environment:
      - DEEP_SEEK_API_KEY=${DEEP_SEEK_API_KEY}
      - DEEP_SEEK_API_URL=${DEEP_SEEK_API_URL}
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - coderbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: coderbot-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_POCKETBASE_URL=http://localhost:8090
    depends_on:
      - backend
    networks:
      - coderbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Code Server IDE (opcional)
  code-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.code-server
    container_name: coderbot-code-server
    ports:
      - "8787:8787"
    volumes:
      - ./:/home/coder/project
      - code_server_data:/home/coder/.local/share/code-server
      - ./docker/code-server-config.yaml:/home/coder/.config/code-server/config.yaml:ro
    networks:
      - coderbot-network
    restart: unless-stopped
    command: --bind-addr 0.0.0.0:8787 --auth none /home/coder/project

volumes:
  # pocketbase_data:  # Comentado para usar dados do Dockerfile
  #   driver: local
  code_server_data:
    driver: local

networks:
  coderbot-network:
    driver: bridge